name: Inventory Checker

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  inventory-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      
      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Verify Python installation
        run: python3 --version
      
      - name: Install pip and script dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Echo message
        run: echo "This is a test"